spring:
  datasource:
    url: jdbc:postgresql://${ip}:5432/springtest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: postgres
    password: dzh123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
ip: localhost