spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springtest
    username: postgres
    password: dzh123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update